image: gradle:7.3.3-jdk17-alpine

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - style
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
    
build:
  stage: build
  script: gradle assemble

style_check:
  stage: style
  script:
    - gradle checkstyleMain
    - gradle checkstyleTest

test:
  stage: test
  script:
    - gradle test
    - gradle AggregateJacocoReport
    # preserve coverage information in an easy-to-reach folder
    - mv build/reports/jacoco/aggregate/html ./coverage
    - mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
    - echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`
  artifacts:
    paths:
      - ./coverage
  coverage: /TestCoverage:(\d+)%/
